version: '3.8'

services:
  web:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api

  api:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./backend/db.sqlite3:/data/db.sqlite3

volumes:
  db_data: