# version: '3.8'

services:
  web:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - api

  api:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./backend/instance/site.db:/data/db.sqlite3  # Mapeia o banco de dados SQLite
    environment:
      SQLITE_DATABASE: /data/db.sqlite3  # Caminho correto do banco no contêiner


# volumes:
#   db_data: