"""profile nullables

Revision ID: 0fe88f168368
Revises: 0aa69e3d149c
Create Date: 2025-02-09 23:09:47.581372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe88f168368'
down_revision = '0aa69e3d149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
